default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: JumpMasterLeaderboardAPI_development

test:
  <<: *default
  database: JumpMasterLeaderboardAPI_test

production:
  <<: *default
  database: JumpMasterLeaderboardAPI_production
  username: JumpMasterLeaderboardAPI
  password: <%= ENV['JUMPMASTERLEADERBOARDAPI_DATABASE_PASSWORD'] %>
